### ISSUE TITLE
Download a student card 

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/playground#20]
the student name of the form is not taken into account

**Comment by ThierryThevenet** [comment]
and the logo is not the correct one

**Comment by vivi-tz** [comment]
@ThierryThevenet The givenName is sent with the certificate, check this: 
https://playground.talao.co/nodejs/student/urn:uuid:7707b6f5-0755-4c02-87a7-e7f7016d89d6?issuer=did%3Aethr%3A0xee09654eedaa79429f8d216fa51a129db0f72250

Regarding the logo, I replaced it with the talao logo for now. If you want something else give me the link and I will configure it, it's in the .env

**Comment by ThierryThevenet** [comment]
it is an issue of the wallet, i will report it
