### ISSUE TITLE
Discount coupon is not available

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/playground#23]

**Comment by vivi-tz** [comment]
@ThierryThevenet I am using this schema: https://github.com/TalaoDAO/wallet-tools/blob/main/test/CredentialOffer2/Voucher.jsonld

and the json that is exposed for this is
https://playground.talao.co/nodejs/discount-offer

I am not sure what is wrong exactly, but this was working previously. I do not understand what goes wrong now.

**Comment by ThierryThevenet** [comment]
the attribute offer is not formatted correctly
