### ISSUE TITLE
different issuer DID

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/playground#28]
it looks like you dont use the same DID for issuing

did:ethr:0xee09654eedaa79429f8d216fa51a129db0f72250" for the voucher

"did:ethr:0xd6008c16068c40c05a5574525db31053ae8b3ba7" for the certificate iof employment

i think teh key i gave you is for did:ethr:0xee09654eedaa79429f8d216fa51a129db0f72250" 
do you use two different keys ?
if not how did you calculate the "did:ethr:0xd6008c16068c40c05a5574525db31053ae8b3ba7" ?

**Comment by vivi-tz** [comment]
@ThierryThevenet I am using a JWK that corresponds to did:ethr:0xd6008c16068c40c05a5574525db31053ae8b3ba7 and I am signing with it.

I am not sure what did:ethr:0xee09654eedaa79429f8d216fa51a129db0f72250 is, it shouldn't appear anywhere. I will look into it.
